### ISSUE TITLE
2 little mistakes

### ISSUE THREAD

**Issue by gallexis** [sakeven/RbTree#1]
Hi, I think I found 2 little mistakes in your code 

**line 281:** `t.root = x`
**should be:** `t.root = y`

**line 153:** `z.parent.parent.color = BLACK`
**should be:** `z.parent.parent.color = RED`

**Comment by sakeven** [comment]
Thanks, I will check it later. 😁

**Comment by Duxy1996** [comment]
The code is 10/10 I tried to do this algorithm and I couldn't.

**Comment by forward32** [comment]
Is this issue resolved?

**Comment by sakeven** [comment]
Fixed, thanks!
