### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TechSgin** [sakeven/RbTree#3]
// this code crash -- randomly add and remove keys

 ltree := NewTree();
 var larr [] int;

 for i := 0; i < 1000000; i++ {
 	lrand := rand.Intn(30);
 	if (lrand > 25) {
 		if len(larr) > 0 {
 			lrand1 := rand.Intn(len(larr));
 			ltree.Delete(key(larr[lrand1]));
 			larr = remove(larr, lrand1);
 			fmt.Printf("delete:[%d] len:[%d]\n", lrand1, len(larr))
 		} 
 	} else {
 		lrand1 := rand.Intn(1000000);
 		larr = append(larr, lrand1);
 		ltree.Insert(key(lrand1), lrand1);
 		fmt.Printf("insert:[%d] len:[%d]\n", lrand1, len(larr));
 	}
 }

**Comment by TechSgin** [comment]
Solved it using doing the following:

1. I have created an extra DeleteNode API (i call it from Delete)
2. I have merged the rbDelteFixup into the DeleteNode (for debugging)

Here are the complete Delete APIs if you would like to fix it.

// Delete deletes the node by key
func (t *Tree) Delete(key keytype) {
	z := t.findnode(key)
	if z == nil {
		return
	}

	t.DeleteNode(z);
}



// Delete deletes the node by key
func (t *Tree) DeleteNode(z *node) {
	if z == nil {
		return
	}
	var l_color int;
	var x, y, xParent, w *node;

	// node to be removed
	y = z

	if y.left == nil {
		// if node have no left then set x to right
		x = y.right
		// t.transplant(z, p_node.right)
	} else if z.right == nil {
		// if node have no right then set x to left
		x = z.left
	} else {
        y = y.right;
        for (y.left != nil) {
            y = y.left;
        }
        x = y.right;
	}

    if(y != z) {
        z.left.parent = y;
        y.left = z.left;
        if(y != z.right) {
            xParent = y.parent;
            if(x != nil) {
                x.parent = y.parent;
            }
            y.parent.left = x;
            y.right = z.right;
            z.right.parent = y;
        } else {
            xParent = y;
        }

        if(t.root == z){
            t.root = y;
        } else if(z.parent.left == z) {
            z.parent.left = y;
        } else {
            z.parent.right = y;
        }

        y.parent = z.parent;
        l_color = y.color;
        y.color = z.color;
        z.color = l_color;
        y = z;
    } else {
        xParent = y.parent;
        if(x != nil) {
            x.parent = y.parent;
        }
        if(t.root == z){
            t.root = x;
        } else if(z.parent.left == z){
            z.parent.left = x;
        } else{
            z.parent.right = x;
        }
    }

    if(y.color != RED) {
        for (x != t.root && (x == nil || x.color == BLACK)) {
            if (x == xParent.left) {
                w = xParent.right;
                if (w.color == RED) {
                    w.color = BLACK;
                    xParent.color = RED;
                    t.leftRotate(xParent);
                    w = xParent.right;
                }
                if( (w.left == nil || w.left.color == BLACK) && (w.right == nil || w.right.color == BLACK) ) {
                    w.color = RED;
                    x = xParent;
                    xParent = xParent.parent;
                } else {
                    if (w.right == nil || w.right.color == BLACK) {
                        if (w.left != nil) {
                            w.left.color = BLACK;
                        }
                        w.color = RED;
                        t.rightRotate(w);
                        w = xParent.right;
                    }
                    w.color = xParent.color;
                    xParent.color = BLACK;
                    if (w.right != nil){
                        w.right.color = BLACK;
                    }
                    t.leftRotate(xParent);
                    break;
                }
            } else {
                w = xParent.left;
                if (w.color == RED) {
                    w.color = BLACK;
                    xParent.color = RED;
                    t.rightRotate(xParent);
                    w = xParent.left;
                }

                if( (w.right == nil || w.right.color == BLACK) && (w.left == nil || w.left.color == BLACK) ) {
                    w.color = RED;
                    x = xParent;
                    xParent = xParent.parent;
                } else {
                    if (w.left == nil || w.left.color == BLACK) {
                        if (w.right != nil){
                            w.right.color = BLACK;
                        }
                        w.color = RED;
                        t.leftRotate(w);
                        w = xParent.left;
                    }
                    w.color = xParent.color;
                    xParent.color = BLACK;
                    if (w.left != nil){
                        w.left.color = BLACK;
                    }
                    t.rightRotate(xParent);
                    break;
                }
            }
        }

        if(x != nil){
            x.color = BLACK;
        }
    }

    t.size--;
}

**Comment by sakeven** [comment]
Fixed
