### ISSUE TITLE
范围查询如何支持

### ISSUE THREAD

**Issue by saddit** [sakeven/RbTree#5]
获取 values = fn（start，end）

**Comment by sakeven** [comment]
红黑树作为 map 或者 dict 的实现，一般没有范围查询，因为不是数组或者队列之类的。
如果已知 start 的 key，可以先通过 FindIt 获得迭代器 it，然后迭代 n 次，来达到类似范围查询的效果。

**Comment by saddit** [comment]
我记得Java是有这个
